# Generated by Django 5.1.7 on 2025-04-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspection',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
