# Generated by Django 5.1.7 on 2025-04-07 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inspections', '0002_inspection_is_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='cooking_outcome',
            field=models.PositiveIntegerField(blank=True, help_text='Percentage score for cooking outcome (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='customer_service',
            field=models.PositiveIntegerField(blank=True, help_text='Percentage score for customer service (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='food_preparation',
            field=models.PositiveIntegerField(blank=True, help_text='Percentage score for food preparation (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='general_hygiene',
            field=models.PositiveIntegerField(blank=True, help_text='Percentage score for general hygiene (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
